spring.application.name=devlair-api
spring.datasource.url=${DEVLAIR_DATABASE_URL:jdbc:postgresql://localhost:5432/devlair}
spring.datasource.username=${DEVLAIR_DATABASE_USERNAME:devlair}
spring.datasource.password=${DEVLAIR_DATABASE_PASSWORD:devlair}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.locations=classpath:db/migration
