import { KiloMessenger } from '../components/KiloMessenger'
import type { Task, WorkspaceData } from '../types'

export function HomeView({ data, onOpenTask, onBrowse }: { data: WorkspaceData; onOpenTask: (task: Task) => void; onBrowse: () => void }) {
  const next = data.tasks.find((task) => task.status === 'AVAILABLE') ?? data.tasks[0]
  return <section className="hq-page"><header className="hq-page__header"><p className="eyebrow">ENGINEERING HOME</p><h1>Good to have you on the team.</h1><p>Your home keeps current work, recent updates, and the skills you have practiced in one place.</p></header>{next ? <section className="assignment-command"><div><span>CURRENT WORK</span><h2>{next.title}</h2><p>{next.summary}</p><div className="tag-row">{next.skills.map((skill) => <small key={skill}>{labelSkill(skill)}</small>)}</div></div><button type="button" onClick={() => onOpenTask(next)}>{next.status === 'COMPLETED' ? 'Review again' : 'Open pull request'}</button></section> : null}<section className="hq-grid"><article className="hq-panel"><p className="panel-label">COMPANY INBOX</p>{data.inbox.map((notice) => <div className="inbox-notice" key={notice.title}><strong>{notice.title}</strong><p>{notice.message}</p></div>)}</article><article className="hq-panel"><p className="panel-label">SKILL SNAPSHOT</p>{data.skills.length ? <div className="skill-list">{data.skills.map((skill) => <div key={skill.skillKey}><span>{labelSkill(skill.skillKey)}</span><b>{skill.bestScore}%</b><meter min="0" max="100" value={skill.bestScore} /></div>)}</div> : <p className="quiet-copy">Your first pull request review will create evidence here. It reflects prepared practice findings, not a rank.</p>}</article><article className="hq-panel"><p className="panel-label">COMPLETED WORK</p><strong>{data.tasks.filter((task) => task.status === 'COMPLETED').length} completed tasks</strong><p className="quiet-copy">Completed work stays available for deliberate practice. Replays help you learn, but future competitive ratings will not reward memorizing feedback.</p><button className="text-action" type="button" onClick={onBrowse}>Open your work queue</button></article></section><KiloMessenger heading="Your next pull request" message="Start with the ticket and architecture note. They explain the system rule the proposed code needs to respect before you write a comment." messageKey="home" /></section>
}

export function labelSkill(skill: string) { return skill.split('-').map((part) => part[0].toUpperCase() + part.slice(1)).join(' ') }
